/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author jens.papenhagen
 */
public class Verkaufladen extends javax.swing.JDialog {

    public int anfang = 0;
    //icon
    Image img = new ImageIcon(Verkaufladen.class.getResource("images/img-fruchte.png")).getImage();

    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public Verkaufladen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        changeAusgabeListe(fruechte());
        progressbarHandler();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        anzeigeListe = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        anzeigeLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auswahlprogramm");
        setIconImage(img);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Listen Auswahl");

        jButton1.setText("Früchte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreuchteButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Gemüse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GemueseButtonActionPerformed(evt);
            }
        });

        anzeigeListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(anzeigeListe);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Auswahl:");

        anzeigeLabel.setText("testtestest");

        jProgressBar1.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(anzeigeLabel))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anzeigeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        anzeigeLabel.getAccessibleContext().setAccessibleName("selectedItem");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GemueseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GemueseButtonActionPerformed
        changeAusgabeListe(gemuese());
    }//GEN-LAST:event_GemueseButtonActionPerformed

    private void FreuchteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreuchteButtonActionPerformed
        changeAusgabeListe(fruechte());
    }//GEN-LAST:event_FreuchteButtonActionPerformed

    /**
     * @return
     */
    private DefaultListModel fruechte() {
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        listModel.addElement("Orange");
        listModel.addElement("Apfel");
        listModel.addElement("Zitrone");
        listModel.addElement("Annanas");
        listModel.addElement("Pfrich");

        return listModel;
    }

    private DefaultListModel gemuese() {
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        listModel.addElement("Kartoffel");
        listModel.addElement("Blumenkohl");
        listModel.addElement("Sellerie");
        listModel.addElement("Möhren");

        return listModel;
    }

    private void changeAusgabeListe(DefaultListModel listModel) {
        MouseListener mouseListener = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                JList theList = (JList) mouseEvent.getSource();
                if (mouseEvent.getClickCount() == 2) {
                    int index = theList.locationToIndex(mouseEvent.getPoint());
                    if (index >= 0) {
                        Object o = theList.getModel().getElementAt(index);
                        changeAusgabeSelectedItem(o.toString());
                    }
                }
            }
        };

        anzeigeListe.setModel(listModel);
        anzeigeListe.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        anzeigeListe.setSelectedIndex(0);
        anzeigeListe.addListSelectionListener(new SharedListSelectionHandler());
        anzeigeListe.addMouseListener(mouseListener);
        anzeigeListe.setVisibleRowCount(5);

        changeIcon(listModel);
    }

    public final void progressbarHandler() {
        jProgressBar1.setValue(anfang);
        jProgressBar1.setStringPainted(true);

        Border border = BorderFactory.createTitledBorder("Loading...");
        jProgressBar1.setBorder(border);
    }

    public int counter() {
        jProgressBar1.setValue(anfang * 3);
        return anfang++;
    }

    public void changeAusgabeSelectedItem(String text) {
        SwingUtilities.invokeLater(() -> {
            anzeigeLabel.setText(text);
            fillTheProgressbar();            
        });
    }

    private void fillTheProgressbar() {
        //start the fillling of the progessbar
        counter();
        if ((counter() * 3) >= 100) {
            changeAusgabeSelectedItem("Progressbar full");
        }
    }

    public void changeIcon(DefaultListModel listModel) {
        Image aktuellesicon = null;
        if (listModel.size() == 5) {
            aktuellesicon = new ImageIcon(Verkaufladen.class.getResource("images/img-fruchte.png")).getImage();
        } else {
            aktuellesicon = new ImageIcon(Verkaufladen.class.getResource("images/img-gemuese.png")).getImage();
        }

        setIconImage(aktuellesicon);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verkaufladen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Verkaufladen dialog = new Verkaufladen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anzeigeLabel;
    private javax.swing.JList<String> anzeigeListe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
